name: common_impls
description: "A new Flutter plugin project."
version: 0.0.2
homepage: "https://github.com/eserdeiro/common_impls"

environment:
  sdk: ^3.5.0
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  in_app_review: ^2.0.9
  plugin_platform_interface: ^2.0.2
  shared_preferences: ^2.3.1
  wortise: ^1.5.1+1

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.eserdeiro.common_impls
        pluginClass: CommonImplsPlugin
      ios:
        pluginClass: CommonImplsPlugin

  # To add assets to your plugin package, add an assets section, like this:
  assets:
    - assets/slide_rating_dialog/
  # For details regarding assets in packages, see
  # https://flutter.dev/to/asset-from-package
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images
  # To add custom fonts to your plugin package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/to/font-from-package
